"""
Fetch Sichuan-Chongqing listed companies from Eastmoney board API.
Outputs SQL INSERT statements to db/seed_companies.sql
"""
import httpx
from pathlib import Path

API = "https://push2.eastmoney.com/api/qt/clist/get"
# Region board codes: m:90+t:1 for region boards
# BK0169 = 四川板块, BK0170 = 重庆板块
BOARDS = {"BK0169": "四川", "BK0170": "重庆"}
OUTPUT = Path(__file__).parent.parent.parent / "db" / "seed_companies.sql"


def fetch_companies() -> list[dict]:
    companies = []
    seen_codes: set[str] = set()
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Referer": "https://quote.eastmoney.com/",
    }
    with httpx.Client(timeout=30, headers=headers) as client:
        for bk_code, region in BOARDS.items():
            params = {
                "pn": "1",
                "pz": "300",
                "po": "1",
                "np": "1",
                "ut": "bd1d9ddb04089700cf9c27f6f7426281",
                "fltt": "2",
                "invt": "2",
                "fid": "f3",
                "fs": f"b:{bk_code}+f:!200",
                "fields": "f12,f14,f26,f100,f102",
            }
            resp = client.get(API, params=params)
            data = resp.json()
            if not data.get("data") or not data["data"].get("diff"):
                continue
            for item in data["data"]["diff"]:
                code = str(item.get("f12", ""))
                if not code or not code.startswith(("0", "3", "6")):
                    continue
                # Deduplicate (a stock could appear in both boards)
                if code in seen_codes:
                    continue
                seen_codes.add(code)

                # f26 is listing date in YYYYMMDD integer format
                raw_listing = item.get("f26")
                listing_date = None
                if raw_listing and isinstance(raw_listing, (int, float)):
                    date_str = str(int(raw_listing))
                    if len(date_str) == 8:
                        listing_date = f"{date_str[:4]}-{date_str[4:6]}-{date_str[6:8]}"

                companies.append({
                    "code": code,
                    "name": str(item.get("f14", "") or ""),
                    "full_name": str(item.get("f14", "") or ""),  # short name as fallback
                    "region": region,
                    "industry": str(item.get("f100", "") or ""),
                    "market": _classify_market(code),
                    "listing_date": listing_date,
                    "registered_city": str(item.get("f102", "") or ""),
                })
    return companies


def _classify_market(code: str) -> str:
    """Classify market tier from stock code prefix."""
    if code.startswith("3"):
        return "创业板"
    if code.startswith("688"):
        return "科创板"
    if code.startswith("8") or code.startswith("4"):
        return "北交所"
    if code.startswith("002"):
        return "中小板"
    return "主板"


def escape_sql(val: str | None) -> str:
    if val is None:
        return "NULL"
    escaped = val.replace("'", "''")
    return f"'{escaped}'"


def generate_sql(companies: list[dict]) -> str:
    from datetime import datetime
    lines = [
        "-- Auto-generated by fetch_company_list.py",
        f"-- Generated at {datetime.now().isoformat()}",
        f"-- {len(companies)} companies from Sichuan + Chongqing region boards",
        "",
    ]
    for c in sorted(companies, key=lambda x: x["code"]):
        cols = "code, name, full_name, region, industry, market, listing_date, registered_city"
        vals = ", ".join(
            escape_sql(c[field])
            for field in ("code", "name", "full_name", "region", "industry", "market", "listing_date", "registered_city")
        )
        lines.append(f"INSERT INTO companies ({cols}) VALUES ({vals}) ON CONFLICT (code) DO NOTHING;")
    return "\n".join(lines) + "\n"


def main():
    print("Fetching Sichuan-Chongqing listed companies...")
    companies = fetch_companies()
    print(f"Found {len(companies)} companies.")
    sql = generate_sql(companies)
    OUTPUT.write_text(sql, encoding="utf-8")
    print(f"Written to {OUTPUT}")


if __name__ == "__main__":
    main()
